1.Program to multiply two given arrays of same size element-by-element.

In [ ]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,2,5])
mul=np.multiply(arr1,arr2)
print('Array multiplication:',mul)

Array multiplication: [ 3  8  6 20]


2. Program to create an element-wise comparison (greater, greater equal, lesser).

In [ ]:
import numpy as np
arr1=np.array([1,6,3,4,])
arr2=np.array([2,4,3,5,])
print('Greater:', np.greater(arr1,arr2))
print('Greater or equal:',np.greater_equal(arr1,arr2))
print('Lesser:',np.less(arr1,arr2))
print('Lesser or equal:',np.less_equal(arr1,arr2))


Greater: [False  True False False]
Greater or equal: [False  True  True False]
Lesser: [ True False False  True]
Lesser or equal: [ True False  True  True]


3. program to create an array of all the even integers from 30 to 70

In [ ]:
import numpy as np
arr=np.arange(30,70,2)
print('Even array:',arr)

Even array: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


4. program to create a 3x3 identity matrix.

In [ ]:
import numpy as np
m=np.identity(3)
print('Identity matrix:\n',m)

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


5. program to create a vector with values from 0 to 20 and change the sign.

In [ ]:
import numpy as np
v=np.arange(0,20)
print('Original vector:',v)
print('Negative vector:',-v)

Original vector: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Negative vector: [  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15 -16 -17
 -18 -19]


6. program to create a 5x5 zero matrix with elements on the main diagonal

In [ ]:
import numpy as np
m=np.diag([3,4,5,6,8])
print('Diagonal matrix:\n',m)

Diagonal matrix:
 [[3 0 0 0 0]
 [0 4 0 0 0]
 [0 0 5 0 0]
 [0 0 0 6 0]
 [0 0 0 0 8]]


7. program to compute sum of all elements, sum of each column and sum of each row.

In [ ]:
import numpy as np
m=[[1,2,3],[6,3,8],[2,9,4]]
print('Sum:',np.sum(m))
print('Sum of coloumns:',np.sum(m,axis=0))
print('Sum of rows:',np.sum(m,axis=1))

Sum: 38
Sum of coloumns: [ 9 14 15]
Sum of rows: [ 6 17 15]


8. program to save a given array to a text file and load it.

9. program to check whether two arrays are equal (element wise) or no

In [ ]:
import numpy as np
arr1=np.array([1,6,3,4,])
arr2=np.array([2,4,3,5,])
print(np.equal(arr1,arr2))

[False False  True False]
